### PR TITLE
Integrate suspended instance

### PR DESCRIPTION
**Pull request by HemaHG**
Signed-off-by: hemahg <hhg@redhat.com>

**What does the PR do**
Integrate suspended instance

### CODE REVIEW

**Review by MikeEdgar — COMMENTED** [review]
I did a quick test with this PR and the status shows as "Degraded".

**Comment by HemaHG** [comment]
Hi @MikeEdgar, I have updated the PR, could you please test it now?
How did you try? I don't have a suspended instance to test.

**Review by MikeEdgar — COMMENTED** [review]
@HemaHG, I think this may still be missing some changes to the `apiStatusToUIStatus` function in `src/app/modules/OpenshiftStreams/components/StreamsTableConnected/useKafkaInstances.ts`

**Comment by HemaHG** [comment]
the SDK https://github.com/redhat-developer/app-services-sdk-js/blob/main/packages/kafka-management-sdk/src/generated/model/kafka-request-all-of.ts#L25 is not updated to show the `suspended`, `suspending` and `resuming` status

**Comment by MikeEdgar** [comment]
@HemaHG , I now see the ":warning: Suspended" displayed, but the transitional states are blank. Suspending and Resuming show neither an icon nor text.

**Review by MikeEdgar — APPROVED** [review]
LGTM :+1: I was testing earlier with an out of date app-services-ui :blush:

**Review by riccardo-forina — APPROVED** [review]

**Pull request merged**
