### PR TITLE
Renamed the Credentials folder that had a trailing space in the name

### PR DESCRIPTION
**Pull request by EricWittmann**
Fixes issue https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/issues/1119

### CODE REVIEW

**Comment by wtrocki** [comment]
@suyash-naithani Do you mind to take look into that. It looks like for case sensitive systems builds might not work well

**Comment by EricWittmann** [comment]
It's not an issue of case sensitivity.  The `src/app/modules/ServiceAccounts/components/Credentials` folder has a trailing space in the name.

Please fix - I still can't clone this repository on Windows.

**Comment by EricWittmann** [comment]
As of today:

```
$ git clone git@github.com:bf2fc6cc711aee1a0c2a/kas-ui.git
Cloning into 'kas-ui'...
remote: Enumerating objects: 14328, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 14328 (delta 163), reused 201 (delta 118), pack-reused 14070
Receiving objects: 100% (14328/14328), 34.70 MiB | 10.37 MiB/s, done.
Resolving deltas: 100% (10025/10025), done.
error: unable to create file src/app/modules/ServiceAccounts/components/Credentials /Credentials.css: No such file or directory
error: unable to create file src/app/modules/ServiceAccounts/components/Credentials /Credentials.tsx: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by riccardo-forina** [comment]
Sorry, I somehow always passed on this. Since it was lagging behind and I couldn't push on your branch @EricWittmann I opened a new one where I cherry-picked your commit and added the fix to the broken imports. It's PR #1223 

I'll close this.

**Pull request closed without merging**
