### PR TITLE
fix: enable multi_az for standard instances

### PR DESCRIPTION
**Pull request by wtrocki**
This fix will switch multi_az flags for standard instances and turn them off for trial ones

### CODE REVIEW

**Comment by wtrocki** [comment]
OMG. Ignore this for now. Formatter killed that file for some reason. I will use --no-verify to avoid linting

**Comment by wtrocki** [comment]
Ready for review

**Comment by wtrocki** [comment]
Requires merge of: https://github.com/redhat-developer/app-services-ui-components/pull/333/files

**Review by ajaypratap003 — APPROVED** [review]
LGTM

**Comment by riccardo-forina** [comment]
Limits and AZ for trial instances
image

**Comment by riccardo-forina** [comment]
And this for standard instances:

image

**Comment by wtrocki** [comment]
LGTM

**Comment by wtrocki** [comment]
Good to merge!

**Comment by jgiardino** [comment]
These updates also look good to me.

**Pull request merged**
